fbgemm:
  parser: fbgemm
  install_script: ./packages/ai_wdl/fbgemm/install_fbgemm_bench.sh
  cleanup_script: ./packages/ai_wdl/fbgemm/cleanup_fbgemm_bench.sh
  path: ./benchmarks/ai_wdl/fbgemm/run.sh
  metrics:
    - bandwidth

rebatch:
  parser: rebatch
  install_script: ./packages/ai_wdl/rebatch/install_rebatch.sh
  cleanup_script: ./packages/ai_wdl/rebatch/cleanup_rebatch.sh
  path: ./benchmarks/ai_wdl/rebatch/rebatchBench
  metrics:
    - bandwidth
    - time_per_batch_us

chm:
  parser: chm
  install_script: ./packages/ai_wdl/chm/install_chm.sh
  cleanup_script: ./packages/ai_wdl/chm/cleanup_chm.sh
  path: ./benchmarks/ai_wdl/chm/chm_bench
  metrics:
    - Mops/sec

deser:
  parser: deser
  install_script: ./packages/ai_wdl/deser/install_deser.sh
  cleanup_script: ./packages/ai_wdl/deser/cleanup_deser.sh
  path: ./benchmarks/ai_wdl/deser/deser_bench
  metrics:
    - Mops/sec

adsim:
  parser: adsim
  install_script: ./packages/adsim/install_adsim.sh
  cleanup_script: ./packages/adsim/cleanup_adsim.sh
  path: ./benchmarks/adsim/run_adsim.py
  roles:
    - client
    - server
  tags:
    scope:
      - app
      - ads
    component:
      - cpu
      - memory
  metrics:
    - final_achieved_qps
    - final_latency_msec
    - final_requested_qps
    - target_latency_msec
    - target_latency_percentile

type_conversion:
  parser: type_conversion
  install_script: ./packages/ai_wdl/type_conversion/install_type_conversion.sh
  cleanup_script: ./packages/ai_wdl/type_conversion/cleanup_type_conversion.sh
  path: ./benchmarks/ai_wdl/type_conversion/type_conversion_bench
  metrics:
    - elem/s
